import{a as l,S as u,i as a}from"./assets/vendor-b11e2a50.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))t(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&t(i)}).observe(document,{childList:!0,subtree:!0});function n(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function t(e){if(e.ep)return;e.ep=!0;const r=n(e);fetch(e.href,r)}})();async function d(s){const o="https://pixabay.com/api/",n=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0}),t=`${o}?${n}`;return(await l.get(t)).data}let c=null;function p(s,o){const n=s.map(t=>`
    <a href="${t.largeImageURL}" class= "gallery-item">
      <img src="${t.webformatURL}" alt="${t.tags}" title="${t.tags}" class="gallery-img" />
      <div class="info">
      <p>Likes <br>${t.likes}</p>
      <p>Views <br>${t.views}</p>
      <p>Comments <br>${t.comments}</p>
      <p>Downloads <br>${t.downloads}</p>
      </div>
    </a>
  `).join("");o.innerHTML=n,c?c.refresh():c=new u(".gallery a")}function m(s){s.innerHTML=""}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".search-form"),o=document.querySelector(".search-input"),n=document.querySelector(".gallery"),t=document.getElementById("loader");s.addEventListener("submit",async e=>{e.preventDefault();const r=o.value.trim();if(r===""){a.error({title:"Error",message:"Please enter a search query",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight"});return}m(n),t.style.display="block";try{const i=await d(r);if(t.style.display="none",i.hits.length===0){a.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",maxWidth:432});return}p(i.hits,n)}catch(i){t.style.display="none",console.error("Error fetching images:",i),a.error({title:"Error",message:"Failed to fetch images. Please try again later.",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",maxWidth:432})}o.value=""})});
//# sourceMappingURL=commonHelpers.js.map
