import{S as L,a as v,i}from"./assets/vendor-b11e2a50.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=n(t);fetch(t.href,s)}})();let p=null;function g(o,e){const n=o.map(r=>`
    <a href="${r.largeImageURL}" class= "gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" class="gallery-img" />
      <div class="info">
      <p>Likes <br>${r.likes}</p>
      <p>Views <br>${r.views}</p>
      <p>Comments <br>${r.comments}</p>
      <p>Downloads <br>${r.downloads}</p>
      </div>
    </a>
  `).join("");e.insertAdjacentHTML("beforeend",n),p?p.refresh():p=new L(".gallery a")}function w(o){o.innerHTML=""}const q=document.querySelector(".gallery");let h=1;async function b(o,e=1){const n="https://pixabay.com/api/",r=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:15}),t=`${n}?${r}`;return(await v.get(t)).data}async function S(o){h+=1;try{const e=await b(o,h);g(e.hits,q);const r=document.querySelector(".gallery-item").getBoundingClientRect().height;return window.scrollBy({left:0,top:r*2,behavior:"smooth"}),e}catch(e){alert(e.message)}}const f=document.querySelector(".search-form"),a=document.querySelector(".btn-load"),c=document.querySelector("#loader"),m=document.querySelector(".gallery");let l="",d=1,y=0;f.addEventListener("submit",o=>{if(o.preventDefault(),l=o.currentTarget.elements.query.value.trim(),!l){i.error({title:"Error",message:"Please enter a search query",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight"});return}d=1,w(m),a.classList.add("btn-load-hidden"),c.style.display="block",b(l,d).then(e=>{if(y=e.totalHits,e.hits.length===0){i.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",maxWidth:432});return}g(e.hits,m),y>15&&a.classList.remove("btn-load-hidden")}).catch(e=>{i.error({title:"Error",message:"Failed to fetch images. Please try again later.",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",maxWidth:432})}).finally(()=>{c.style.display="none",f.reset()})});a.addEventListener("click",()=>{c.style.display="block",a.classList.add("btn-load-hidden"),S(l).then(o=>{d+=1,d*15>=o.totalHits?(a.classList.add("btn-load-hidden"),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#B8E3FF",closeOnClick:!0,position:"topRight",maxWidth:432})):a.classList.remove("btn-load-hidden")}).finally(()=>{c.style.display="none"})});
//# sourceMappingURL=commonHelpers.js.map
