import{a as b,S as L,i}from"./assets/vendor-b11e2a50.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))r(e);new MutationObserver(e=>{for(const s of e)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function n(e){const s={};return e.integrity&&(s.integrity=e.integrity),e.referrerPolicy&&(s.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?s.credentials="include":e.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(e){if(e.ep)return;e.ep=!0;const s=n(e);fetch(e.href,s)}})();async function m(o,t=1){const n="https://pixabay.com/api/",r=new URLSearchParams({key:"43954842-86e0551d49d52b31999082e7b",q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:15}),e=`${n}?${r}`;return(await b.get(e)).data}let p=null;function f(o,t){const n=o.map(r=>`
    <a href="${r.largeImageURL}" class= "gallery-item">
      <img src="${r.webformatURL}" alt="${r.tags}" title="${r.tags}" class="gallery-img" />
      <div class="info">
      <p>Likes <br>${r.likes}</p>
      <p>Views <br>${r.views}</p>
      <p>Comments <br>${r.comments}</p>
      <p>Downloads <br>${r.downloads}</p>
      </div>
    </a>
  `).join("");t.insertAdjacentHTML("beforeend",n),p?p.refresh():p=new L(".gallery a")}function w(o){o.innerHTML=""}const g=document.querySelector(".search-form"),a=document.querySelector(".btn-load"),d=document.querySelector("#loader"),h=document.querySelector(".gallery");let c="",l=1,y=0;g.addEventListener("submit",async o=>{if(o.preventDefault(),c=o.currentTarget.elements.query.value.trim(),!c){i.error({title:"Error",message:"Please enter a search query",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight"});return}l=1,w(h),a.classList.add("btn-load-hidden"),d.style.display="block";try{const t=await m(c,l);if(y=t.totalHits,t.hits.length===0){i.warning({title:"No Results",message:"Sorry, there are no images matching your search query. Please try again!",backgroundColor:"#EF4040",closeOnClick:!0,position:"topRight",maxWidth:432});return}f(t.hits,h),y>15&&a.classList.remove("btn-load-hidden")}catch{i.error({title:"Error",message:"Something went wrong. Please try again!",closeOnClick:!0,position:"topRight"})}finally{d.style.display="none",g.reset()}});a.addEventListener("click",async()=>{l+=1,d.style.display="block",a.classList.add("btn-load-hidden");try{const o=await m(c,l);f(o.hits,h);const n=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({left:0,top:n*2,behavior:"smooth"}),l*15>=y?(a.classList.add("btn-load-hidden"),i.info({title:"Info",message:"We're sorry, but you've reached the end of search results.",backgroundColor:"#B8E3FF",closeOnClick:!0,position:"topRight",maxWidth:432})):a.classList.remove("btn-load-hidden")}catch{i.error({title:"Error",message:"Something went wrong. Please try again!",closeOnClick:!0,position:"topRight"})}finally{d.style.display="none"}});
//# sourceMappingURL=commonHelpers.js.map
